name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up JDK    
      uses: actions/setup-java@v1 
      with:        
        java-version: 1.17
    - name: Build with Maven      
      run: mvn package
    - name: Docker build
      run: docker build . --tag registry.vimuens.nl/watcherz-userservice:latest
    - name: Publish to Docker Registry
      run: docker push registry.vimuens.nl/watcherz-userservice:latest
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: apply -f kubernetes
